import os, json, random, requests, markdown, urllib.parse, feedparser, time, re, sys, io
from datetime import datetime

sys.stdout = io.TextIOWrapper(sys.stdout.detach(), encoding='utf-8')
sys.stderr = io.TextIOWrapper(sys.stderr.detach(), encoding='utf-8')

def log(msg): print(f"[{datetime.now().strftime('%H:%M:%S')}] {msg}")

# [Configuration] 2호기 아이덴티티 강화
GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY", "")
BLOG_TITLE = "TECH ALPHA"
BLOG_DESC = "Next-Generation Wealth & Future Gadget Intel"
BLOG_BASE_URL = "https://ramuh18.github.io/dividend-compounding/"
EMPIRE_URL = "https://empire-analyst.digital/"
HISTORY_FILE = "history.json"

# [Monetization] 1호기 수익화 링크
AFFILIATE_LINK = "https://www.bybit.com/invite?ref=DOVWK5A" 
AMAZON_LINK = f"https://www.amazon.com/s?k=ledger+nano+x&tag=empireanalyst-20"

# ==========================================
# [FALLBACK] 2호기 전용 1,500자 리포트 (1호기와 내용 다름)
# ==========================================
FALLBACK_REPORT = """
## The Silicon Frontier: Redefining Digital Asset Security in 2026

The intersection of advanced robotics and decentralized finance has created a new frontier for capital growth. As we move deeper into the decade, the security of digital assets is no longer a technical detail—it is the foundation of modern wealth.

### 1. The Rise of Hardware-Based Sovereignty
As AI-driven cyber threats evolve, the reliance on centralized exchanges is plummeting. Smart money is migrating toward physical security protocols. Cold storage is the new 'Gold Vault.' To survive this era, one must possess absolute control over their private keys, shielded by institutional-grade encryption.

### 2. High-Growth Tech Convergence
The next wave of 'Alpha' isn't coming from traditional stocks. It's emerging from the synergy between autonomous systems and blockchain liquidity. We are tracking a mass shift where value is generated by machine-to-machine transactions, demanding a completely new set of tools for the modern investor.

### 3. Conclusion: The Strategic Edge
In a world of synthetic data, verifiable scarcity is the ultimate luxury. Aligning your portfolio with hardware security and frontier tech is the only way to maintain a strategic edge over the automated market.
"""

def generate_part(topic, focus):
    safety = [{"category": f"HARM_CATEGORY_{c}", "threshold": "BLOCK_NONE"} for c in ["HARASSMENT", "HATE_SPEECH", "SEXUALLY_EXPLICIT", "DANGEROUS_CONTENT"]]
    prompt = f"Write a professional tech gadgets and wealth report on '{topic}'. Focus: {focus}. 500 words. Institutional tone. English Only."
    try:
        url = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key={GEMINI_API_KEY}"
        resp = requests.post(url, json={"contents": [{"parts": [{"text": prompt}]}], "safetySettings": safety, "generationConfig": {"temperature": 0.5}}, timeout=35)
        if resp.status_code == 200:
            return resp.json()['candidates'][0]['content']['parts'][0]['text']
    except: pass
    return ""

def create_slim_bw_html(topic, img_url, body_html, sidebar_html, canonical_url):
    return f"""<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{topic}</title>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;900&display=swap" rel="stylesheet">
    <style>
        :root {{ --bg: #ffffff; --text: #000000; --line: #e5e7eb; }}
        body {{ font-family: 'Inter', sans-serif; line-height: 1.8; color: var(--text); background: var(--bg); margin: 0; }}
        header {{ padding: 20px 50px; border-bottom: 1px solid var(--line); display: flex; justify-content: space-between; align-items: center; background: #fff; position: sticky; top: 0; z-index: 100; }}
        .container {{ max-width: 1350px; margin: 0 auto; display: grid; grid-template-columns: 1fr; gap: 60px; padding: 50px 20px; }}
        @media(min-width: 1000px) {{ .container {{ grid-template-columns: 1fr 350px; }} }}
        h1 {{ font-size: 3.5rem; font-weight: 900; line-height: 1.1; margin: 0 0 30px 0; letter-spacing: -2px; text-transform: uppercase; }}
        .featured-img {{ width: 100%; height: 450px; object-fit: cover; border: 1px solid #000; margin-bottom: 30px; }}
        /* 슬림한 안내 박스 */
        .info-bar {{ padding: 15px; border-top: 2px solid #000; border-bottom: 2px solid #000; margin: 30px 0; font-weight: 700; font-size: 0.9rem; text-align: center; text-transform: uppercase; letter-spacing: 1px; }}
        .sidebar {{ position: sticky; top: 100px; height: fit-content; border-left: 1px solid var(--line); padding-left: 40px; }}
        .ad-btn {{ display: block; padding: 18px; margin-bottom: 12px; text-decoration: none; text-align: center; font-weight: 900; background: #000; color: #fff; font-size: 0.8rem; letter-spacing: 1px; }}
        .content {{ font-size: 1.25rem; color: #374151; }}
        footer {{ background: #000; color: #666; padding: 60px 0; text-align: center; font-size: 0.8rem; margin-top: 100px; }}
    </style></head>
    <body>
    <header><div style="font-weight:900;">{BLOG_TITLE}</div><a href="{EMPIRE_URL}" style="color:#000; text-decoration:none; font-size:0.8rem; font-weight:bold;">HQ ACCESS →</a></header>
    <div class="container">
        <main>
            <h1 style="border-bottom: 10px solid #000; padding-bottom: 15px;">{topic}</h1>
            <img src="{img_url}" class="featured-img">
            <div class="info-bar">
                Latest Insight from <a href="{EMPIRE_URL}" style="color:#000;">Empire Analyst HQ</a>: 2026 Asset Security Protocols are now Live.
            </div>
            <div class="content">{body_html}</div>
            <div style="margin-top:50px; padding:30px; background:#f9fafb; border:1px solid #000;">
                🚀 <b>Deep Analysis:</b> Access full-tier algorithmic signals at our <a href="{EMPIRE_URL}" style="color:#000; font-weight:900;">Private Wealth Terminal →</a>
            </div>
        </main>
        <aside class="sidebar">
            <h4 style="margin-top:0; text-transform:uppercase; color:#999; font-size:0.75rem; letter-spacing:2px;">Strategic Terminal</h4>
            <a href="{EMPIRE_URL}" class="ad-btn">Access HQ</a>
            <a href="{AFFILIATE_LINK}" class="ad-btn" style="background:#fff; color:#000; border:1px solid #000;">Bybit $30k Bonus</a>
            <a href="{AMAZON_LINK}" class="ad-btn" style="background:#fff; color:#000; border:1px solid #000;">Secure Ledger</a>
            <h4 style="margin-top:50px; text-transform:uppercase; color:#999; font-size:0.75rem; letter-spacing:2px;">Recent Intel</h4>
            <ul style="list-style:none; padding:0; font-size:0.9rem;">{sidebar_html}</ul>
        </aside>
    </div>
    <footer>
        <p>&copy; 2026 {BLOG_TITLE}. Part of the Empire Analyst Network.</p>
        <p style="opacity:0.5; font-size:0.7rem;"><b>Amazon Disclaimer:</b> As an Amazon Associate, I earn from qualifying purchases.</p>
    </footer></body></html>"""

def main():
    log("🏁 Striker #2 Unique B&W Started")
    topic = "The Convergence Of Robotics And Wealth Protection" # 1호기와 다른 주제
    p1 = generate_part(topic, "Tech Innovation")
    p2 = generate_part(topic, "Asset Security")
    p3 = generate_part(topic, "Future Outlook")
    full_content = f"{p1}\n\n{p2}\n\n{p3}"
    if len(full_content) < 1000: full_content = FALLBACK_REPORT
    
    html_body = markdown.markdown(full_content)
    # 이미지 키워드를 'gadget, hardware, minimal'로 바꿔 1호기와 차별화
    img_url = f"https://image.pollinations.ai/prompt/{urllib.parse.quote('high tech minimal hardware gadget black and white studio lighting 8k')}"
    
    history = []
    if os.path.exists(HISTORY_FILE):
        with open(HISTORY_FILE, "r", encoding="utf-8") as f: history = json.load(f)
    sidebar_html = "".join([f"<li style='margin-bottom:12px;'><a href='{BLOG_BASE_URL}{h['file']}' style='text-decoration:none; color:#4b5563;'>• {h['title']}</a></li>" for h in history[:5]])
    
    archive_name = f"post_{datetime.now().strftime('%Y%m%d_%H%M')}.html"
    history.insert(0, {"date": datetime.now().strftime("%Y-%m-%d"), "title": topic, "file": archive_name})
    with open(HISTORY_FILE, "w", encoding="utf-8") as f: json.dump(history, f, indent=4)
    
    with open("index.html", "w", encoding="utf-8") as f: f.write(create_slim_bw_html(topic, img_url, html_body, sidebar_html, f"{BLOG_BASE_URL}{archive_name}"))
    with open(archive_name, "w", encoding="utf-8") as f: f.write(create_slim_bw_html(topic, img_url, html_body, sidebar_html, f"{BLOG_BASE_URL}{archive_name}"))
    log("✅ Task Complete")

if __name__ == "__main__": main()
