import os, json, random, requests, markdown, urllib.parse, feedparser, time, re, sys, io
from datetime import datetime

sys.stdout = io.TextIOWrapper(sys.stdout.detach(), encoding='utf-8')
sys.stderr = io.TextIOWrapper(sys.stderr.detach(), encoding='utf-8')

def log(msg): print(f"[{datetime.now().strftime('%H:%M:%S')}] {msg}")

# [Configuration]
GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY", "")
BLOG_TITLE = "FUTURE INTELLIGENCE"
BLOG_BASE_URL = "https://ramuh18.github.io/dividend-compounding/"
EMPIRE_URL = "https://empire-analyst.digital/"
HISTORY_FILE = "history.json"

# [Monetization] 1호기 수익화 로직 완전 이식
AFFILIATE_LINK = "https://www.bybit.com/invite?ref=DOVWK5A" 
AMAZON_LINK = f"https://www.amazon.com/s?k=ledger+nano+x&tag=empireanalyst-20"

# ==========================================
# [FALLBACK CONTENT] API 실패 시 삽입될 고품질 리포트
# ==========================================
FALLBACK_REPORT = """
## The Paradigm Shift: Artificial Intelligence and Global Economic Architecture

The rapid evolution of artificial intelligence is no longer a peripheral technological trend but the central pillar of a new global economic architecture. As we transition into an era defined by cognitive automation, the traditional boundaries of market productivity and asset valuation are being fundamentally rewritten. 

### 1. The Proliferation of Generative Intelligence
The integration of large language models and autonomous agents into enterprise workflows has catalyzed an unprecedented leap in operational efficiency. Unlike previous industrial revolutions, the AI transformation impacts the high-skill service sector, creating a dual-track economy where 'Alpha' is generated by those who successfully bridge the gap between human intuition and machine precision.

### 2. Strategic Wealth Shifts and Digital Sovereignty
As AI consumes a larger share of global GDP, the concept of wealth preservation has evolved. Digital sovereignty and hardware-based security have become paramount. For institutional and private investors alike, securing the 'keys' to their digital kingdom via cold storage and decentralized protocols is no longer optional—it is a strategic necessity for long-term survival in an automated market.

### 3. Future Trajectory: Beyond 2026
The coming years will see the emergence of 'General Intelligence' components that will manage entire supply chains and financial portfolios with minimal human oversight. This shift necessitates a complete re-evaluation of current asset allocation strategies. To remain competitive, one must look toward platforms that provide deep-tier intelligence and institutional-grade market analysis.
"""

def clean_ai_output(text):
    if not text or "error" in text.lower() or "queue full" in text.lower(): return ""
    text = re.sub(r'\{"role":.*?"content":', '', text, flags=re.DOTALL)
    text = text.replace('"}', '').replace('"', '').replace("'", "")
    return text.strip()

def generate_part(topic, focus):
    safety = [{"category": f"HARM_CATEGORY_{c}", "threshold": "BLOCK_NONE"} for c in ["HARASSMENT", "HATE_SPEECH", "SEXUALLY_EXPLICIT", "DANGEROUS_CONTENT"]]
    prompt = f"Write a 450-word institutional analysis on '{topic}'. Focus: {focus}. Markdown. English Only."
    for attempt in range(2): # 시도 횟수 제한으로 무한 로딩 방지
        try:
            url = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key={GEMINI_API_KEY}"
            resp = requests.post(url, json={"contents": [{"parts": [{"text": prompt}]}], "safetySettings": safety, "generationConfig": {"temperature": 0.4}}, timeout=30)
            if resp.status_code == 200:
                res = clean_ai_output(resp.json()['candidates'][0]['content']['parts'][0]['text'])
                if len(res) > 300: return res
        except: pass
        time.sleep(2)
    return ""

def create_wide_bw_html(topic, img_url, body_html, sidebar_html, canonical_url):
    return f"""<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><title>{topic}</title>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;900&display=swap" rel="stylesheet">
    <style>
        :root {{ --bg: #ffffff; --text: #000000; }}
        body {{ font-family: 'Inter', sans-serif; line-height: 1.8; color: var(--text); background: var(--bg); margin: 0; }}
        header {{ padding: 25px 60px; border-bottom: 2px solid #000; background: #fff; display: flex; justify-content: space-between; align-items: center; position: sticky; top: 0; z-index: 1000; }}
        .container {{ max-width: 1400px; margin: 0 auto; display: grid; grid-template-columns: 1fr; gap: 80px; padding: 60px 20px; }}
        @media(min-width: 1000px) {{ .container {{ grid-template-columns: 1fr 400px; }} }}
        h1 {{ font-size: 4.5rem; font-weight: 900; line-height: 1.0; margin: 0 0 40px 0; letter-spacing: -4px; text-transform: uppercase; }}
        .featured-img {{ width: 100%; height: 550px; object-fit: cover; filter: grayscale(100%); border: 1px solid #000; }}
        .sidebar {{ position: sticky; top: 120px; height: fit-content; border-left: 3px solid #000; padding-left: 50px; }}
        .ad-btn {{ display: block; padding: 20px; margin-bottom: 15px; text-decoration: none; text-align: center; font-weight: 900; background: #000; color: #fff; text-transform: uppercase; font-size: 0.9rem; letter-spacing: 2px; }}
        .content {{ font-size: 1.35rem; text-align: justify; }}
        footer {{ background: #000; color: #666; padding: 80px 0; text-align: center; font-size: 0.8rem; margin-top: 100px; }}
    </style></head>
    <body>
    <header><div style="font-weight:900; font-size:1.6rem;">{BLOG_TITLE}</div><a href="{EMPIRE_URL}" style="color:#000; text-decoration:none; font-weight:900; border:3px solid #000; padding:8px 20px;">ACCESS HQ</a></header>
    <div class="container">
        <main>
            <h1>{topic}</h1>
            <img src="{img_url}" class="featured-img">
            <div style="background:#000; color:#fff; padding:50px; margin:50px 0; font-size:1.3rem; border-left: 10px solid #666;">
                Standard intelligence is currently being synchronized. <a href="{EMPIRE_URL}" style="color:#fff; font-weight:900; text-decoration:underline;">Access the Full 2026 Private Terminal at Empire Analyst HQ →</a>
            </div>
            <div class="content">{body_html}</div>
        </main>
        <aside class="sidebar">
            <h4 style="text-transform:uppercase; letter-spacing:4px; font-size:0.8rem; margin-bottom:40px; color:#999;">Strategic Access</h4>
            <a href="{EMPIRE_URL}" class="ad-btn">Empire Analyst HQ</a>
            <a href="{AFFILIATE_LINK}" class="ad-btn" style="background:#fff; color:#000; border:3px solid #000;">Bybit $30k Bonus</a>
            <a href="{AMAZON_LINK}" class="ad-btn" style="background:#fff; color:#000; border:3px solid #000;">Secure Your Ledger</a>
            <h4 style="margin-top:80px; text-transform:uppercase; letter-spacing:4px; font-size:0.8rem; color:#999;">Recent Intel</h4>
            <ul style="list-style:none; padding:0; font-size:1rem; line-height:2.6;">{sidebar_html}</ul>
        </aside>
    </div>
    <footer>
        <p>&copy; 2026 {BLOG_TITLE}. A Member of the Empire Analyst Network.</p>
        <p style="max-width:850px; margin:30px auto; opacity:0.6; line-height:1.8;"><b>Amazon Disclaimer:</b> As an Amazon Associate, I earn from qualifying purchases. Content is for professional informational purposes only.</p>
    </footer></body></html>"""

def main():
    log("🏁 Striker #2 Robust B&W Started")
    topic = "The Convergence of Artificial Intelligence and Future Asset Structures"
    
    # 3단계 시도
    p1 = generate_part(topic, "Core Innovation")
    p2 = generate_part(topic, "Economic Impact")
    p3 = generate_part(topic, "Future Outlook")
    
    full_content = f"{p1}\n\n{p2}\n\n{p3}"
    
    # [핵심] 만약 API 결과가 부실하면 미리 준비된 FALLBACK_REPORT로 본문을 교체하여 퀄리티 보장
    if len(full_content) < 800:
        log("⚠️ API output insufficient. Deploying High-Quality Fallback Intelligence.")
        full_content = FALLBACK_REPORT
    
    html_body = markdown.markdown(full_content)
    img_url = f"https://image.pollinations.ai/prompt/{urllib.parse.quote('minimal professional humanoid robot black and white fine art 8k')}"
    
    history = []
    if os.path.exists(HISTORY_FILE):
        with open(HISTORY_FILE, "r", encoding="utf-8") as f: history = json.load(f)
    sidebar_html = "".join([f"<li><a href='{BLOG_BASE_URL}{h['file']}' style='text-decoration:none; color:#000; font-weight:900;'>• {h['title']}</a></li>" for h in history[:6]])
    
    archive_name = f"post_{datetime.now().strftime('%Y%m%d_%H%M')}.html"
    history.insert(0, {"date": datetime.now().strftime("%Y-%m-%d"), "title": topic, "file": archive_name})
    with open(HISTORY_FILE, "w", encoding="utf-8") as f: json.dump(history, f, indent=4)
    
    full_html = create_wide_bw_html(topic, img_url, html_body, sidebar_html, f"{BLOG_BASE_URL}{archive_name}")
    with open("index.html", "w", encoding="utf-8") as f: f.write(full_html)
    with open(archive_name, "w", encoding="utf-8") as f: f.write(full_html)
    log(f"✅ Mission Complete: {len(full_content)} characters.")

if __name__ == "__main__": main()
